services:
  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10


  worker:
    build: .
    command: celery -A app.celery_app.app worker -Q default -l info --concurrency=4
    environment:
      - DB_ADMIN=postgresql://postgres:postgres@host.docker.internal:6432/hakaton
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      redis:
        condition: service_healthy

  api:
    build: .
    command: uvicorn app.main_api:api --host 0.0.0.0 --port 8000
    environment:
      - DB_ADMIN=postgresql://postgres:postgres@host.docker.internal:6432/hakaton
      - PARSER_SERVICE_URL=http://parser:8000
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      parser:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - "8010:8000"

  parser:
    build: .
    command: uvicorn app.main_parser:app --host 0.0.0.0 --port 8000
    environment:
      - DB_ADMIN=postgresql://postgres:postgres@host.docker.internal:6432/hakaton
      - NUM_WORKERS=4
    ports:
      - "8001:8000"

  beat:
    build: .
    command: celery -A app.celery_app.app beat -l info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      redis:
        condition: service_healthy